import Head from "next/head";
import "../styles/globals.css";
import Navbar from "../components/Navbar";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["300", "400", "500"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export const metadata = {
  title: 'Next example',
  description: 'Generated by create next app',
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head></Head>
      <body className={roboto.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
